Update Build OPlus Kernel.yml

diff --git a/.github/workflows/Build OPlus Kernel.yml b/.github/workflows/Build OPlus Kernel.yml
--- a/.github/workflows/Build OPlus Kernel.yml
+++ b/.github/workflows/Build OPlus Kernel.yml
@@ -748,7 +748,7 @@ jobs:
           elif [[ "$KSU_META" == "KernelSU-Next" ]]; then
             echo "Configure KernelSU Next..."
             curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/refs/heads/${MANAGER_BRANCH}/kernel/setup.sh" | bash -s dev_susfs
-            cd ./KernelSU-Next
+            cd KernelSU-Next
             KSU_VERSION=$(expr $(curl -sI "https://api.github.com/repos/KernelSU-Next/KernelSU-Next/commits?sha=${MANAGER_BRANCH}&per_page=1" | grep -i "link:" | sed -n 's/.*page=\([0-9]*\)>; rel="last".*/\1/p') "+" 30000)
             echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
             sed -i "s/KSU_VERSION_FALLBACK := 1/KSU_VERSION_FALLBACK := $KSU_VERSION/g" kernel/Kbuild
@@ -758,7 +758,9 @@ jobs:
               | head -n 1 \
               | sed 's/"name": "//;s/"//')
             sed -i "s/KSU_VERSION_TAG_FALLBACK := v0.0.1/KSU_VERSION_TAG_FALLBACK := $KSU_GIT_TAG/g" kernel/Kbuild
+            
             # List of Patch Files
+            cd ../common/drivers/kernelsu
             patches=(
               "overwrite_hook_mode.patch"
             )
@@ -767,7 +769,7 @@ jobs:
             echo "Downloading $p..."
             wget -q https://github.com/AndreiMikh/OPlus-Action-Build/raw/refs/heads/LiquidAndrei/patches/$p -O ./$p
             echo "Applying $p..."
-            patch -p1 -N -F 3 < $p || echo "⚠ Patch $p May have Already been Applied or Failed"
+            patch -p2 -N -F 3 < $p || echo "⚠ Patch $p May have Already been Applied or Failed"
             done
               echo "KernelSU-Next Custom Patches Complete"  
 
