Update KSU Meta V2.yml

diff --git a/.github/workflows/KSU Meta V2.yml b/.github/workflows/KSU Meta V2.yml
--- a/.github/workflows/KSU Meta V2.yml
+++ b/.github/workflows/KSU Meta V2.yml
@@ -1264,18 +1264,18 @@ jobs:
           # Clone SUSFS Repos (Primary + Fallback)
           # ==============================
           echo "Cloning SUSFS4OKI..."
-          git clone --depth=1 -b $SUSFS_BRANCH https://github.com/cctv18/susfs4oki.git susfs4oki || echo "SUSFS4OKI Not Found"
+          git clone --depth=1 -b $SUSFS_BRANCH https://github.com/cctv18/susfs4oki.git ../../susfs4oki || echo "SUSFS4OKI not found"
 
           echo "Cloning SUSFS4KSU (fallback)..."
-          git clone --depth=1 -b $SUSFS_BRANCH https://gitlab.com/simonpunk/susfs4ksu.git susfs4ksu || echo "SUSFS4KSU Not Found"
+          git clone --depth=1 -b $SUSFS_BRANCH https://gitlab.com/simonpunk/susfs4ksu.git ../../susfs4ksu || echo "SUSFS4KSU not found"
 
           # ==============================
           # Detect which SUSFS Repository was Cloned & Get Version
           # ==============================
-          if [ -d "susfs4oki" ]; then
-              SUS_DIR="susfs4oki"
-          elif [ -d "susfs4ksu" ]; then
-              SUS_DIR="susfs4ksu"
+          if [ -d "../../susfs4oki" ]; then
+              SUS_DIR="../../susfs4oki/susfs4ksu"  # Correct Internal Folder
+          elif [ -d "../../susfs4ksu" ]; then
+              SUS_DIR="../../susfs4ksu"
           else
               echo "ERROR: No SUSFS Repository Found!"
               exit 1
