Update Main-Build.yml

diff --git a/.github/workflows/Main-Build.yml b/.github/workflows/Main-Build.yml
--- a/.github/workflows/Main-Build.yml
+++ b/.github/workflows/Main-Build.yml
@@ -162,7 +162,13 @@ on:
         
       SCHED:
         type: boolean
-        description: "Apply HMBIRD? (SM-8750)"
+        description: "Apply HMBIRD (SM-8750)?"
+        required: true
+        default: false
+
+      ADIOS:
+        type: boolean
+        description: "Apply ADIOS I/O Scheduler"
         required: true
         default: false
         
@@ -520,6 +526,7 @@ jobs:
               echo "SUSFS_DEV         : ${{ github.event.inputs.SUSFS_DEV }}"
               echo "FAST_BUILD        : ${{ github.event.inputs.FAST_BUILD }}"
               echo "SCHED             : ${{ github.event.inputs.SCHED }}"
+              echo "ADIOS             : ${{ github.event.inputs.ADIOS }}"
               echo "UNICODE_BYPASS    : ${{ github.event.inputs.UNICODE_BYPASS }}"
               echo "XUS_FIX           : ${{ github.event.inputs.XUS_FIX }}"
               
@@ -1611,6 +1618,38 @@ jobs:
           dos2unix "${PATCH_FILE}" || true
           patch -p1 -F 3 < "${PATCH_FILE}"
           echo "Patch Complete"
+
+      - name: Adaptive I/O Scheduler
+        if: ${{ github.event.inputs.ADIOS == 'true' }}
+        run: |
+          set -euo pipefail
+          cd kernel_workspace/kernel_platform/common || exit 1
+
+          # Detect DefConfig Path
+          if [[ -f ../common/arch/arm64/configs/gki_defconfig ]]; then
+            DEFCONFIG="../common/arch/arm64/configs/gki_defconfig"
+          elif [[ -f ../arch/arm64/configs/gki_defconfig ]]; then
+            DEFCONFIG="../arch/arm64/configs/gki_defconfig"
+          else
+            echo "GKI DefConfig Not Found!"
+            exit 1
+          fi
+
+          # Check if Adaptive I/O Scheduler Source Exists
+          if [[ ! -f ../drivers/block/mq-iosched/adios-iosched.c ]]; then
+            echo "⚠ Adaptive I/O Scheduler Source Not Found, Skipping Adaptive IO Scheduler Configuration"
+            exit 0
+          fi
+
+          # Remove Old Adaptive I/O Scheduler Entries to Prevent Duplication
+          sed -i '/CONFIG_MQ_IOSCHED_ADIOS/d' "$DEFCONFIG"
+          sed -i '/CONFIG_MQ_IOSCHED_DEFAULT_ADIOS/d' "$DEFCONFIG"
+
+          # Enable Adaptive I/O Scheduler
+          echo "CONFIG_MQ_IOSCHED_ADIOS=y" >> "$DEFCONFIG"
+          echo "CONFIG_MQ_IOSCHED_DEFAULT_ADIOS=y" >> "$DEFCONFIG"
+
+          echo "✅ Adaptive I/O Scheduler Enabled in $DEFCONFIG"
 
       - name: LSM BBG
         if: ${{ github.event.inputs.LSM == 'true' }}
