Update Main Kernel Builder.yml

diff --git a/.github/workflows/Main Kernel Builder.yml b/.github/workflows/Main Kernel Builder.yml
--- a/.github/workflows/Main Kernel Builder.yml
+++ b/.github/workflows/Main Kernel Builder.yml
@@ -401,11 +401,22 @@ jobs:
           remove-codeql: true           # Remove CodeQL to Free Space
 
       - name: 🔧 Install and Cache Build Dependencies
+        shell: bash
         run: |
           # Install Required Build Dependencies with APT Package Caching
           export APTPACKAGES="bc build-essential bison clang curl dos2unix elfutils flex gawk git kmod lld llvm libdw-dev libelf-dev liblz4-tool libncurses-dev libssl-dev libxml2-utils python3 rsync unzip zip zlib1g-dev"
-          bash "$GITHUB_WORKSPACE/kernel_workspace/AndreiMikh-Kernel-Lab/scripts/APT-Packages.sh" ~/.apt-pkg-cache
+          
+          SCRIPT="$GITHUB_WORKSPACE/kernel_workspace/AndreiMikh-Kernel-Lab/scripts/APT-Packages.sh"
 
+          # Verify APT Package Caching Script Exists
+          if [ ! -f "$SCRIPT" ]; then
+            echo "⚠️ APT Packages Script Not Found: $SCRIPT"
+            exit 1
+          fi
+
+          # Execute APT Package Caching Script
+          bash "$SCRIPT" ~/.apt-pkg-cache
+    
       - name: 🔧 Setup Kotlin
         run: |
           set -euo pipefail
