Update Main.yml

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -1305,13 +1305,14 @@ jobs:
           # ==============================
           # Apply KernelSU 10 Enable SUSFS Patch
           # ==============================
-          if [[ "${{ github.event.inputs.KSU_META }}" == "KernelSU" ]]; then          
-              echo "KernelSU Type Detected, Preparing SUSFS Enable Patch..."
+          if [[ "${{ github.event.inputs.KSU_META }}" == "KernelSU" || \
+                "${{ github.event.inputs.KSU_META }}" == "KernelSU-Next" ]]; then
+              echo "✅ KernelSU or KernelSU-Next Detected — Applying Relevant Configuration..."
           
               if [[ "${{ github.event.inputs.SUSFS_VERSION }}" == "OGKI" ]]; then
-                  PATCH_URL="https://raw.githubusercontent.com/cctv18/susfs4oki/oki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch"
+                PATCH_URL="https://raw.githubusercontent.com/cctv18/susfs4oki/oki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch"
               else
-                  PATCH_URL="https://gitlab.com/simonpunk/susfs4ksu/-/raw/gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch"
+                PATCH_URL="https://gitlab.com/simonpunk/susfs4ksu/-/raw/gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch"
               fi
           
               echo "Downloading from: $PATCH_URL"
@@ -1319,18 +1320,18 @@ jobs:
               wget -q "$PATCH_URL" -O enable_susfs.patch || true
           
               if [[ -f "enable_susfs.patch" ]]; then
-                  echo "Applying Patch Inside $KDIR"
+                echo "Applying Patch Inside $KDIR"
           
-                  patch -d "$KDIR" -p1 --forward < enable_susfs.patch || true
+                patch -d "$KDIR" -p1 --forward < enable_susfs.patch || true
           
-                  rm -f enable_susfs.patch
+                rm -f enable_susfs.patch
           
-                  echo "✅ 10 Enable SUSFS Patch Applied!"
+                echo "✅ 10 Enable SUSFS Patch Applied!"
               else
-                  echo "⚠️ Patch Not Found, Skipping"
+                echo "⚠️ Patch Not Found, Skipping"
               fi
           else
-              echo "❌ KernelSU Not Selected, Skipping SUSFS Enable Patch"
+            echo "❌ KernelSU Not Selected, Skipping SUSFS Enable Patch"
           fi
 
           cd - >/dev/null
