Update Test-Build.yml

diff --git a/.github/workflows/Test-Build.yml b/.github/workflows/Test-Build.yml
--- a/.github/workflows/Test-Build.yml
+++ b/.github/workflows/Test-Build.yml
@@ -692,7 +692,7 @@ jobs:
           fi
 
           if [ -n "$BRANCH" ]; then
-            echo "KANDROID_VERSION=${BRANCH%-*}" >> $GITHUB_ENV
+            echo "ANDROID-VERSION=${BRANCH%-*}" >> $GITHUB_ENV
             echo "KERNEL_VERSION=${BRANCH#*-}" >> $GITHUB_ENV
             echo "Branch found: $BRANCH"
           else
@@ -750,7 +750,7 @@ jobs:
           cd kernel_workspace
 
           SUFFIX="${{ github.event.inputs.SUFFIX }}"
-          KANDROID_VERSION="${{ env.KANDROID_VERSION }}"
+          ANDROID-VERSION="${{ env.ANDROID-VERSION }}"
           FASTBUILD="${{ github.event.inputs.FASTBUILD }}"
 
           echo "Injecting Custom Kernel Suffix: $SUFFIX"
@@ -771,14 +771,14 @@ jobs:
 
             if grep -q 'KERNELVERSION.*scm_version' "$path"; then
               echo "New SetLocalVersion Format Detected"
-              sed -i "s|echo \"\${KERNELVERSION}.*scm_version}\"|echo \"\${KERNELVERSION}-${KANDROID_VERSION}-${SUFFIX}\"|" "$path"
+              sed -i "s|echo \"\${KERNELVERSION}.*scm_version}\"|echo \"\${KERNELVERSION}-${ANDROID-VERSION}-${SUFFIX}\"|" "$path"
 
             elif grep -q 'echo "\$res"' "$path"; then
               echo "Old SetLocalVersion Format Detected"
 
               if [ "$FASTBUILD" = "true" ]; then
                 echo "Fast Build Enabled: Setting Static Res Value"
-                sed -i "s/^res=.*/res=\"-${KANDROID_VERSION}-${SUFFIX}\"/" "$path"
+                sed -i "s/^res=.*/res=\"-${ANDROID-VERSION}-${SUFFIX}\"/" "$path"
               else
                 echo "Standard Build: Dynamically Injecting Suffix"
                 if [[ -f ./kernel_platform/build_with_bazel.py ]]; then
@@ -805,7 +805,7 @@ jobs:
         run: |
           cd kernel_workspace
 
-          KANDROID_VERSION="${{ env.KANDROID_VERSION }}"
+          ANDROID-VERSION="${{ env.ANDROID-VERSION }}"
           FASTBUILD="${{ github.event.inputs.FASTBUILD }}"
 
           echo "Generating Random Kernel Suffix..."
@@ -831,14 +831,14 @@ jobs:
 
             if grep -q 'KERNELVERSION.*scm_version' "$path"; then
               echo "New SetLocalVersion Format Detected"
-              sed -i "s|echo \"\${KERNELVERSION}.*scm_version}\"|echo \"\${KERNELVERSION}-${KANDROID_VERSION}-${AUTO_SUFFIX}\"|" "$path"
+              sed -i "s|echo \"\${KERNELVERSION}.*scm_version}\"|echo \"\${KERNELVERSION}-${ANDROID-VERSION}-${AUTO_SUFFIX}\"|" "$path"
 
             elif grep -q 'echo "\$res"' "$path"; then
               echo "Old SetLocalVersion Format Detected"
 
               if [ "$FASTBUILD" = "true" ]; then
                 echo "Fast Build: Using Static Res with Random Suffix"
-                sed -i "s/^res=.*/res=\"-${KANDROID_VERSION}-${AUTO_SUFFIX}\"/" "$path"
+                sed -i "s/^res=.*/res=\"-${ANDROID-VERSION}-${AUTO_SUFFIX}\"/" "$path"
               else
                 echo "Standard Build: Injecting Random Suffix Dynamically"
                 tac "$path" | sed "0,/echo \"\\\$res\"/s//res=\\\$(echo \\\$res | cut -d- -f1-2)-${AUTO_SUFFIX}; echo \"\\\$res\";/" | tac > "$path.tmp"
@@ -1018,8 +1018,8 @@ jobs:
             # ==============================
             # Generate Commit-Based Version
             # ==============================
-            KSU_VERSION=$(( $(git rev-list --count main 2>/dev/null || echo 114514) + 37185 ))
-            echo "KSUVER=$KSU_VERSION" >> "$GITHUB_ENV"
+            KSU-META-VERSION=$(( $(git rev-list --count main 2>/dev/null || echo 114514) + 37185 ))
+            echo "KSU-META-VER=$KSU-META-VERSION" >> "$GITHUB_ENV"
 
             echo "SukiSU-Ultra Version: v${KSU_API_VERSION}-${GIT_COMMIT_HASH}"
 
@@ -1036,8 +1036,8 @@ jobs:
 
             cd ./KernelSU || exit 1
 
-            KSU_VERSION=$(( $(git rev-list --count main 2>/dev/null || echo 114514) + 30700 ))
-            echo "KSUVER=$KSU_VERSION" >> "$GITHUB_ENV"
+            KSU-META-VERSION=$(( $(git rev-list --count main 2>/dev/null || echo 114514) + 30700 ))
+            echo "KSU-META-VER=$KSU-META-VERSION" >> "$GITHUB_ENV"
 
             # ==============================
             # Detect DefConfig Path
@@ -1059,7 +1059,7 @@ jobs:
             # ==============================
             # Add Formatted Name
             # ==============================
-            printf 'CONFIG_KSU_FULL_NAME_FORMAT="ReSukiSU-%%TAG_NAME%%[%s]"\n' "$KSU_VERSION" >> "$DEFCONFIG"
+            printf 'CONFIG_KSU_FULL_NAME_FORMAT="ReSukiSU-%%TAG_NAME%%[%s]"\n' "$KSU-META-VERSION" >> "$DEFCONFIG"
             
           elif [[ "$KSU-META" == "KernelSU-Next" ]]; then
             echo "Configuring KernelSU-Next..."
@@ -1072,11 +1072,11 @@ jobs:
 
             cd ./KernelSU-Next || exit 1
 
-            KSU_VERSION=$(get_commit_count_version "$REPO" "$MANAGER_BRANCH" 30000)
-            echo "KSUVER=$KSU_VERSION" >> "$GITHUB_ENV"
+            KSU-META-VERSION=$(get_commit_count_version "$REPO" "$MANAGER_BRANCH" 30000)
+            echo "KSU-META-VER=$KSU-META-VERSION" >> "$GITHUB_ENV"
 
             sed -i \
-              "s/KSU_VERSION_FALLBACK := 1/KSU_VERSION_FALLBACK := $KSU_VERSION/" \
+              "s/KSU_VERSION_FALLBACK := 1/KSU_VERSION_FALLBACK := $KSU-META-VERSION/" \
               kernel/Kbuild
 
             KSU_GIT_TAG=$(get_latest_tag "$REPO")
@@ -1123,11 +1123,11 @@ jobs:
 
             cd ./Wild_KSU || exit 1
 
-            KSU_VERSION=$(get_commit_count_version "$REPO" "$MANAGER_BRANCH" 30000)
-            echo "KSUVER=$KSU_VERSION" >> "$GITHUB_ENV"
+            KSU-META-VERSION=$(get_commit_count_version "$REPO" "$MANAGER_BRANCH" 30000)
+            echo "KSU-META-VER=$KSU-META-VERSION" >> "$GITHUB_ENV"
 
             sed -i \
-              "s/KSU_VERSION_FALLBACK := 1/KSU_VERSION_FALLBACK := $KSU_VERSION/" \
+              "s/KSU_VERSION_FALLBACK := 1/KSU_VERSION_FALLBACK := $KSU-META-VERSION/" \
               kernel/Kbuild
 
             KSU_GIT_TAG=$(get_latest_tag "$REPO")
@@ -1147,16 +1147,16 @@ jobs:
 
             cd ./KernelSU || exit 1
 
-            KSU_VERSION=$(get_commit_count_version "$REPO" "$MANAGER_BRANCH" 30000)
-            echo "KSUVER=$KSU_VERSION" >> "$GITHUB_ENV"
+            KSU-META-VERSION=$(get_commit_count_version "$REPO" "$MANAGER_BRANCH" 30000)
+            echo "KSU-META-VER=$KSU-META-VERSION" >> "$GITHUB_ENV"
 
             sed -i \
-              "s/KSU_VERSION_FALLBACK := 1/KSU_VERSION_FALLBACK := $KSU_VERSION/" \
+              "s/KSU_VERSION_FALLBACK := 1/KSU_VERSION_FALLBACK := $KSU-META-VERSION/" \
               kernel/Kbuild
 
             KSU_GIT_TAG=$(get_latest_tag "$REPO")
 
-            sed -i "s/^DKSU_VERSION=16$/DKSU_VERSION=${KSU_VERSION}/" kernel/Kbuild
+            sed -i "s/^DKSU_VERSION=16$/DKSU_VERSION=${KSU-META-VERSION}/" kernel/Kbuild
 
           else
             echo "No built-in KSU Meta Selected, Skipping..."
@@ -1176,15 +1176,15 @@ jobs:
           echo "=========================="
 
           echo "====== Adding SUSFS ======"
-          echo "Android: ${{ env.KANDROID_VERSION }}"
+          echo "Android: ${{ env.ANDROID-VERSION }}"
           echo "Kernel:  ${{ env.KERNEL_VERSION }}"
           echo "=========================="
 
           # ==============================
           # Detect Kernel Base
           # ==============================
-          GKI_V="${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}"
-          echo "Detected GKI Version: $GKI_V"
+          GKI-OKI-VERSION="${{ env.ANDROID-VERSION }}-${{ env.KERNEL_VERSION }}"
+          echo "Detected GKI Version: $GKI-OKI-VERSION"
 
           # ==============================
           # Detect Correct Kernel Common Directory
@@ -1203,7 +1203,7 @@ jobs:
           # ==============================
           # Clone Correct SUSFS Repository (Select Between SUSFS OGKI / GKI)
           # ==============================
-          if [[ ("$GKI_V" == "android14-6.1" || "$GKI_V" == "android15-6.6" || "$GKI_V" == "android16-6.12") && "${{ github.event.inputs.SUSFS-VERSION }}" == "OGKI" ]]; then
+          if [[ ("$GKI-OKI-VERSION" == "android14-6.1" || "$GKI-OKI-VERSION" == "android15-6.6" || "$GKI-OKI-VERSION" == "android16-6.12") && "${{ github.event.inputs.SUSFS-VERSION }}" == "OGKI" ]]; then
               echo "If Both Conditions are Met, Executing Specific Logic of SUSFS OGKI Repository"
 
               # Check for SUSFS OGKI Development Branch if Selected
@@ -1211,12 +1211,12 @@ jobs:
                   echo "Cloning SUSFS OGKI Development Branch"
                   git clone --depth=1 \
                      https://github.com/cctv18/susfs4oki.git susfs4ksu \
-                     -b "oki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}-dev"
+                     -b "oki-${{ env.ANDROID-VERSION }}-${{ env.KERNEL_VERSION }}-dev"
               else
                   echo "Cloning SUSFS OGKI Main Branch"
                   git clone --depth=1 \
                      https://github.com/cctv18/susfs4oki.git susfs4ksu \
-                     -b oki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}
+                     -b oki-${{ env.ANDROID-VERSION }}-${{ env.KERNEL_VERSION }}
               fi
           
           elif [[ "${{ github.event.inputs.SUSFS-VERSION }}" == "GKI" ]]; then
@@ -1227,12 +1227,12 @@ jobs:
                   echo "Cloning SUSFS GKI Development Branch"
                   git clone --depth=1 \
                      https://gitlab.com/simonpunk/susfs4ksu.git susfs4ksu \
-                     -b "gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}-dev"
+                     -b "gki-${{ env.ANDROID-VERSION }}-${{ env.KERNEL_VERSION }}-dev"
               else
                   echo "Cloning SUSFS GKI Main Branch"
                   git clone --depth=1 \
                      https://gitlab.com/simonpunk/susfs4ksu.git susfs4ksu \
-                     -b gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}
+                     -b gki-${{ env.ANDROID-VERSION }}-${{ env.KERNEL_VERSION }}
               fi
           else
               echo "ERROR: Invalid SUSFS Version Selected!"
@@ -1265,10 +1265,10 @@ jobs:
           # ==============================
           # Detect SUSFS Patch File
           # ==============================
-          SUS_PATCH=$(ls ./susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}*.patch 2>/dev/null | head -n1)
+          SUS_PATCH=$(ls ./susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ env.ANDROID-VERSION }}-${{ env.KERNEL_VERSION }}*.patch 2>/dev/null | head -n1)
 
           if [ -z "$SUS_PATCH" ]; then
-            echo "ERROR: SUSFS Patch Not Found for $GKI_V"
+            echo "ERROR: SUSFS Patch Not Found for $GKI-OKI-VERSION"
             echo "Available Patches:"
             ls ./susfs4ksu/kernel_patches/ || true
             exit 1
@@ -1294,9 +1294,9 @@ jobs:
           # ==============================
           # Hide Patch (Only Supported Bases)
           # ==============================
-          if [[ "$GKI_V" == "android14-6.1" || \
-                "$GKI_V" == "android15-6.1" || \
-                "$GKI_V" == "android15-6.6" ]]; then
+          if [[ "$GKI-OKI-VERSION" == "android14-6.1" || \
+                "$GKI-OKI-VERSION" == "android15-6.1" || \
+                "$GKI-OKI-VERSION" == "android15-6.6" ]]; then
 
               echo "Applying Hide Patch"
 
@@ -1316,9 +1316,9 @@ jobs:
               echo "KernelSU Type Detected, Preparing SUSFS Enable Patch..."
           
               if [[ "${{ github.event.inputs.SUSFS-VERSION }}" == "OGKI" ]]; then
-                  PATCH_URL="https://raw.githubusercontent.com/cctv18/susfs4oki/oki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch"
+                  PATCH_URL="https://raw.githubusercontent.com/cctv18/susfs4oki/oki-${{ env.ANDROID-VERSION }}-${{ env.KERNEL_VERSION }}/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch"
               else
-                  PATCH_URL="https://gitlab.com/simonpunk/susfs4ksu/-/raw/gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch"
+                  PATCH_URL="https://gitlab.com/simonpunk/susfs4ksu/-/raw/gki-${{ env.ANDROID-VERSION }}-${{ env.KERNEL_VERSION }}/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch"
               fi
           
               echo "Downloading from: $PATCH_URL"
@@ -1382,13 +1382,13 @@ jobs:
           
           cd ./kernel_platform/common
 
-          GKI_V="${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}"
+          GKI-OKI-VERSION="${{ env.ANDROID-VERSION }}-${{ env.KERNEL_VERSION }}"
           SUBLEVEL=$(grep '^SUBLEVEL *=' Makefile | head -n1 | cut -d= -f2 | tr -d ' ')
 
           # ==============================
           # 5.15 Legacy C Library Compatibility Fix
           # ==============================
-          if [ "$GKI_V" == "android13-5.15" ] && [ "$SUBLEVEL" -lt 123 ]; then
+          if [ "$GKI-OKI-VERSION" == "android13-5.15" ] && [ "$SUBLEVEL" -lt 123 ]; then
             echo "Apply Legacy Fix for Kernel 5.15.0–5.15.123 (Old Libc Compatibility Issue)"
 
             cp ../../AndreiMikh-Kernel-Lab/patches/Legacy-5.15-Fix ./Legacy-5.15-Fix.patch
@@ -1415,8 +1415,8 @@ jobs:
               echo "Fixing Missing TrustyOS in 6.6.0–6.6.30 Kernel Source & Manifest (SUSFS Error Fix)"
 
               # Update the Patch to Fix TrustyOS Issues
-              sed -i 's/-32,12 +32,38/-32,11 +32,37/g' 50_add_susfs_in_gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.patch
-              sed -i '/#include <trace\/hooks\/fs.h>/d' 50_add_susfs_in_gki-${{ env.KANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.patch
+              sed -i 's/-32,12 +32,38/-32,11 +32,37/g' 50_add_susfs_in_gki-${{ env.ANDROID-VERSION }}-${{ env.KERNEL_VERSION }}.patch
+              sed -i '/#include <trace\/hooks\/fs.h>/d' 50_add_susfs_in_gki-${{ env.ANDROID-VERSION }}-${{ env.KERNEL_VERSION }}.patch
             fi
           fi
 
@@ -1428,7 +1428,7 @@ jobs:
             fake_patched=0
 
             # Apply Fake Patch for Specific Android Versions
-            if [ "$GKI_V" = "android15-6.6" ]; then
+            if [ "$GKI-OKI-VERSION" = "android15-6.6" ]; then
               if ! grep -qxF $'\tunsigned int nr_subpages = __PAGE_SIZE / PAGE_SIZE;' ./fs/proc/task_mmu.c; then
                 echo "NR Subpages Not Found, Apply Temporary Fix"
 
@@ -1442,7 +1442,7 @@ jobs:
             fi
 
             # Handle Other Android Versions
-            if [ "$GKI_V" = "android14-6.1" ]; then
+            if [ "$GKI-OKI-VERSION" = "android14-6.1" ]; then
               if ! grep -qxF $'\tif (!vma_pages(vma))' ./fs/proc/task_mmu.c; then
                 echo "VMA Pages Not Found, Apply Temporary Fix"
                 fake_patched=1
@@ -1456,7 +1456,7 @@ jobs:
             fi
 
             # Handle Android 12 / 13 Versions
-            if [ "$GKI_V" = "android12-5.10" ] || [ "$GKI_V" = "android13-5.15" ]; then
+            if [ "$GKI-OKI-VERSION" = "android12-5.10" ] || [ "$GKI-OKI-VERSION" = "android13-5.15" ]; then
               if ! grep -qxF $'\tif (!vma_pages(vma))' ./fs/proc/task_mmu.c; then
                 echo "VMA Pages Not Found, Apply Temporary Fix"
                 fake_patched=1
@@ -1469,7 +1469,7 @@ jobs:
             if [ "$fake_patched" = 1 ]; then
 
               # Revert Fake Patches Based on Kernel Version
-              if [ "$GKI_V" = "android15-6.6" ]; then
+              if [ "$GKI-OKI-VERSION" = "android15-6.6" ]; then
                 if grep -qxF $'\tunsigned int nr_subpages = __PAGE_SIZE / PAGE_SIZE;' ./fs/proc/task_mmu.c; then
                   sed -i \
                     -e '/unsigned int nr_subpages \= __PAGE_SIZE \/ PAGE_SIZE;/d' \
@@ -1478,9 +1478,9 @@ jobs:
                 fi
               fi
 
-              if [ "$GKI_V" = "android12-5.10" ] || \
-                 [ "$GKI_V" = "android13-5.15" ] || \
-                 [ "$GKI_V" = "android14-6.1" ]; then
+              if [ "$GKI-OKI-VERSION" = "android12-5.10" ] || \
+                 [ "$GKI-OKI-VERSION" = "android13-5.15" ] || \
+                 [ "$GKI-OKI-VERSION" = "android14-6.1" ]; then
 
                 if grep -qxF $'\t\tgoto show_pad;' ./fs/proc/task_mmu.c; then
                   sed -i -e 's/goto show_pad;/return 0;/' ./fs/proc/task_mmu.c
@@ -1718,14 +1718,14 @@ jobs:
           if [[ "$SUSFS-META" != "-1" ]]; then
 
             # Full vs Minimal SUSFS
-            if [[ "$GKI_V" == "android14-6.1" || \
-                  "$GKI_V" == "android15-6.6" || \
-                  "$GKI_V" == "android16-6.12" ]]; then
+            if [[ "$GKI-OKI-VERSION" == "android14-6.1" || \
+                  "$GKI-OKI-VERSION" == "android15-6.6" || \
+                  "$GKI-OKI-VERSION" == "android16-6.12" ]]; then
               SUSFS_CONFIG="FULL"
-              echo "✅ Supported GKI Version Detected: $GKI_V → Using FULL SUSFS"
+              echo "✅ Supported GKI Version Detected: $GKI-OKI-VERSION → Using FULL SUSFS"
             else
               SUSFS_CONFIG="MINIMAL"
-              echo "⚠ Unsupported GKI Version: $GKI_V → Using Minimal SUSFS"
+              echo "⚠ Unsupported GKI Version: $GKI-OKI-VERSION → Using Minimal SUSFS"
             fi
 
             # Base SUSFS Settings (Common)
@@ -2227,7 +2227,7 @@ jobs:
       - name: Upload AnyKernel3
         uses: actions/upload-artifact@v4
         with:
-          name: "${{ steps.extract_info.outputs.value }}(${{ env.TKERNEL_VERSION }})-${{ github.event.inputs.KSU-META-SOURCE }}(${{ env.KSUVER }})"
+          name: "${{ steps.extract_info.outputs.value }}(${{ env.TKERNEL_VERSION }})-${{ github.event.inputs.KSU-META-SOURCE }}(${{ env.KSU-META-VER }})"
           path: ./AnyKernel3/*
           
       - name: Extract & Process ZRAM Module
